changelog:
  categories:
    - title: Enhancements
      labels:
        - "enhancement"
    - title: Documentation
      labels:
        - "documentation"
    - title: Bugs fixed
      labels:
        - "bug"
    - title: Other Changes
      labels:
        - "*"
