version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "18"
  commands:
  - python -m pip install pip --upgrade
  - python -m pip install --upgrade --requirement tests_requirements.txt
  - tox -e doc
  - mkdir -p $READTHEDOCS_OUTPUT/html
  - cp -r doc/_build/html/* $READTHEDOCS_OUTPUT/html
