# This file is used to create and configure simulated DotBot instances for the simulator.
# It is only used when the flag `-p dotbot-simulator` is set, otherwise it is ignored.

[[dotbots]]
address = "BADCAFE111111111" # DotBot unique address
calibrated = 0xff # optional, defaults to only first lighthouse calibrated
pos_x = 400 # [0, 2_000] in mm
pos_y = 400 # [0, 2_000]
direction = 0 # [0, 360] in degrees, 0 is facing north, increasing clockwise

[[dotbots]]
address = "DEADBEEF22222222"
pos_x = 400
pos_y = 200
direction = 180

[[dotbots]]
address = "B0B0F00D33333333"
pos_x = 1_500
pos_y = 1_500
direction = 180

[[dotbots]]
address = "BADC0DE444444444"
pos_x = 1_000
pos_y = 1_000
direction = 360
