[[dotbots]]
address = "BADCAFE111111111" # DotBot unique address
calibrated = 0xff # optional, defaults to all possible lighthouses calibrated
pos_x = 400 # [0, 1_000_000]
pos_y = 200 # [0, 1_000_000]
direction = 0 # [0, 360]

[[dotbots]]
address = "DEADBEEF22222222"
calibrated = 0xff
pos_x = 300
pos_y = 200
direction = 90

[[dotbots]]
address = "B0B0F00D33333333"
calibrated = 0xff
pos_x = 1_000
pos_y = 1_000
direction = 90

[[dotbots]]
address = "BADC0DE444444444"
calibrated = 0xff
pos_x = 500
pos_y = 500
direction = 180

[[dotbots]]
address = "5555555555555555"
calibrated = 0xff
pos_x = 810
pos_y = 870
direction = 180

[[dotbots]]
address = "6666666666666666"
calibrated = 0xff
pos_x = 280
pos_y = 880
direction = 180

[[dotbots]]
address = "7777777777777777"
calibrated = 0xff
pos_x = 120
pos_y = 990
direction = 180

[[dotbots]]
address = "8888888888888888"
calibrated = 0xff
pos_x = 800
pos_y = 560
direction = 180

[[dotbots]]
address = "9999999999999999"
calibrated = 0xff
pos_x = 990
pos_y = 180
direction = 65

[[dotbots]]
address = "A000000000000000"
calibrated = 0xff
pos_x = 900
pos_y = 800
direction = 123
