name: CI

on:
  push:
    branches:
      - develop
    pull_request:
      branches:
      - develop
    tags:
      - '*'

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade --requirement tests_requirements.txt
        python -m pip install --upgrade .
    - name: Run tests
      run: pytest
    - name: Check style
      run: |
        flake8
        pylint bot_controller --rcfile=setup.cfg
        black --check --diff .
    - name: Build a package tarball
      run: python -m build -n
    - name: Check package
      run: twine check dist/*
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@master
      if: >-
        github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      with:
        user: __token__
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@master
      if: >-
        github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
