name: CI

on:
  push:
    branches:
      - develop
    tags:
      - '*'
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade --requirement tests_requirements.txt
        python -m pip install --upgrade .
    - name: Run tox
      run: |
        export CFLAGS=`python -c 'import sysconfig;print("-I"+sysconfig.get_paths()["include"])'`
        export PY38_PATH=`python -c 'import sysconfig;print(sysconfig.get_paths()["include"])'`
        mkdir -p $PY38_PATH/../../lib/python3.8/site-packages/bot_controller/frontend/build
        tox
    - name: Build a package tarball
      run: python -m build -n
    # - name: Publish package to TestPyPI
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   if: >-
    #     github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    #   with:
    #     user: __token__
    #     password: ${{ secrets.test_pypi_password }}
    #     repository_url: https://test.pypi.org/legacy/
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: >-
        github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
